// Local type for preset entries; avoids importing from types.ts
export type PresetInstrument = {
  id: string
  manufacturer?: string
  model: string
  artist?: string
  introduced?: number
  country?: string
  players?: string[]
  info?: string

  units: 'inch' | 'mm'
  mode: 'equal' | 'curved'
  strings: number
  frets: number

  // equal
  scale?: number

  // curved
  scaleTreble?: number
  scaleBass?: number
  anchorFret?: number
  curvedExponent?: number

  // common
  stringSpanNut: number
  stringSpanBridge: number
  overhang: number
}

/**
 * NOTE:
 * - units: "inch" (all measurements in inches; UI converts mm↔inch automatically)
 * - stringSpanNut / stringSpanBridge: E–E (center-to-center of outer strings)
 * - overhang: outer string center to fretboard edge
 * - anchorFret: neutral fret for curved/fan-fret (typically 7–12)
 */

export const PRESETS: PresetInstrument[] = [
  // ---------------- G U I T A R S ----------------
  {
    id: 'ormsby-hype-gtr6-ms',
    manufacturer: 'Ormsby',
    model: 'Hype GTR 6 Multi-Scale',
    introduced: 2010,
    country: 'Australia',
    info: 'Typical Ormsby 6-string multiscale. Specs may vary per run.',
    units: 'inch',
    mode: 'curved',
    strings: 6, frets: 24,
    // common Ormsby 6 MS: ~25.5–27.5"
    scaleTreble: 25.5, scaleBass: 27.5, anchorFret: 12,
    stringSpanNut: 1.37, stringSpanBridge: 2.00, overhang: 0.10,
  },
  {
    id: 'ormsby-goliath-gtr7-ms',
    manufacturer: 'Ormsby',
    model: 'Goliath GTR 7 Multi-Scale',
    introduced: 2015,
    country: 'Australia',
    info: 'Typical Ormsby 7-string multiscale. Specs may vary per run.',
    units: 'inch',
    mode: 'curved',
    strings: 7, frets: 24,
    // common 7 MS: ~25.5–27.0"
    scaleTreble: 25.5, scaleBass: 27.0, anchorFret: 12,
    stringSpanNut: 1.77, stringSpanBridge: 2.28, overhang: 0.12,
  },
  {
    id: 'ormsby-hype-gtr8-ms',
    manufacturer: 'Ormsby',
    model: 'Hype GTR 8 Multi-Scale',
    introduced: 2016,
    country: 'Australia',
    info: 'Typical Ormsby 8-string multiscale. Specs may vary per run.',
    units: 'inch',
    mode: 'curved',
    strings: 8, frets: 24,
    // common 8 MS: ~26.5–28.0"
    scaleTreble: 26.5, scaleBass: 28.0, anchorFret: 12,
    stringSpanNut: 2.13, stringSpanBridge: 2.75, overhang: 0.12,
  },
  {
    id: 'fender-stratocaster-clapton',
    manufacturer: 'Fender',
    model: 'Stratocaster',
    artist: 'Eric Clapton',
    introduced: 1954,
    country: 'USA',
    players: ['Jimi Hendrix', 'Eric Clapton', 'Mark Knopfler', 'Stevie Ray Vaughan'],
  info: 'Three single coils and comfy body contours made the Strat a modern standard by the late 1950s.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 25.5,
    stringSpanNut: 1.41, stringSpanBridge: 2.07, overhang: 0.12,
  },
  {
    id: 'fender-telecaster-52',
    manufacturer: 'Fender',
    model: 'Telecaster ’52',
    introduced: 1950,
    country: 'USA',
    players: ['Keith Richards', 'Bruce Springsteen', 'Prince', 'Muddy Waters'],
  info: 'The first mass-produced solidbody. Simple construction with legendary twang.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 21, scale: 25.5,
    stringSpanNut: 1.41, stringSpanBridge: 2.08, overhang: 0.12,
  },
  {
    id: 'gibson-les-paul-slash',
    manufacturer: 'Gibson',
    model: 'Les Paul Standard',
    artist: 'Slash',
    introduced: 1952,
    country: 'USA',
    players: ['Slash', 'Jimmy Page', 'Gary Moore', 'Joe Perry'],
  info: 'Thick mahogany + maple cap with humbuckers (1957→) created singing rock sustain.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.43, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'gibson-sg-angus',
    manufacturer: 'Gibson',
    model: 'SG Standard',
    artist: 'Angus Young',
    introduced: 1961,
    country: 'USA',
    players: ['Angus Young', 'Tony Iommi', 'Robby Krieger'],
  info: 'Light, thin body with easy upper-fret access — a hard rock workhorse.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.43, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'prs-custom24',
    manufacturer: 'PRS',
    model: 'Custom 24',
    introduced: 1985,
    country: 'USA',
    players: ['Mark Tremonti', 'Orianthi', 'Myles Kennedy (PRS)'],
  info: 'PRS flagship: 24 frets, excellent finish, and balanced tone.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 25.0,
    stringSpanNut: 1.39, stringSpanBridge: 2.06, overhang: 0.11,
  },
  {
    id: 'prs-santana',
    manufacturer: 'PRS',
    model: 'Santana',
    artist: 'Carlos Santana',
    introduced: 1995,
    country: 'USA',
    players: ['Carlos Santana'],
  info: 'PRS’s first widely sold artist model; 24½" scale and singing sustain.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 24.5,
    stringSpanNut: 1.39, stringSpanBridge: 2.06, overhang: 0.11,
  },
  {
    id: 'ibanez-jem7v',
    manufacturer: 'Ibanez',
    model: 'JEM7V',
    artist: 'Steve Vai',
    introduced: 1987,
    country: 'Japan',
    players: ['Steve Vai'],
  info: 'Superstrat with “monkey grip” and double-locking tremolo — a shred cornerstone.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 25.5,
    stringSpanNut: 1.42, stringSpanBridge: 2.13, overhang: 0.10,
  },
  {
    id: 'jackson-randy-rhoads',
    manufacturer: 'Jackson',
    model: 'Randy Rhoads',
    artist: 'Randy Rhoads',
    introduced: 1983,
    country: 'USA',
    players: ['Randy Rhoads', 'Phil Demmel'],
  info: 'Asymmetric V-shape designed for fast metal playing.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 25.5,
    stringSpanNut: 1.42, stringSpanBridge: 2.13, overhang: 0.10,
  },
  {
    id: 'evh-wolfgang',
    manufacturer: 'EVH',
    model: 'Wolfgang Special',
    artist: 'Eddie Van Halen',
    introduced: 2009,
    country: 'USA / MEX / JPN',
    players: ['Eddie Van Halen'],
  info: 'EVH brand’s modern workhorse; Floyd-style bridge and hot humbuckers.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 25.5,
    stringSpanNut: 1.43, stringSpanBridge: 2.00, overhang: 0.10,
  },
  {
    id: 'gretsch-6120',
    manufacturer: 'Gretsch',
    model: '6120 “Chet Atkins”',
    artist: 'Brian Setzer',
    introduced: 1954,
    country: 'USA',
    players: ['Chet Atkins', 'Brian Setzer', 'Eddie Cochran'],
  info: 'Hollow body with Filter’Tron pickups — an orange rockabilly icon.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.6,
    stringSpanNut: 1.45, stringSpanBridge: 2.20, overhang: 0.12,
  },
  {
    id: 'rickenbacker-360-12',
    manufacturer: 'Rickenbacker',
    model: '360/12',
    artist: 'George Harrison',
    introduced: 1964,
    country: 'USA',
    players: ['George Harrison', 'Roger McGuinn', 'Tom Petty'],
  info: 'Classic 12-string jangle for 1960s pop and folk rock.',
    units: 'inch',
    mode: 'equal',
    strings: 12, frets: 21, scale: 24.75,
    stringSpanNut: 1.65, stringSpanBridge: 2.12, overhang: 0.10,
  },
  {
    id: 'gibson-es-335',
    manufacturer: 'Gibson',
    model: 'ES-335',
    introduced: 1958,
    country: 'USA',
    players: ['Larry Carlton', 'Noel Gallagher', 'Eric Clapton (varh.)'],
  info: 'Semi-hollow with center block: sustain without typical hollow-body feedback.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.42, stringSpanBridge: 2.02, overhang: 0.12,
  },
  {
    id: 'fender-jazzmaster',
    manufacturer: 'Fender',
    model: 'Jazzmaster',
    introduced: 1958,
    country: 'USA',
    players: ['Nels Cline', 'J Mascis', 'Kevin Shields'],
  info: 'Offset body and floating vibrato — from surf to modern indie.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 21, scale: 25.5,
    stringSpanNut: 1.42, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'fender-jaguar',
    manufacturer: 'Fender',
    model: 'Jaguar',
    introduced: 1962,
    country: 'USA',
    players: ['Johnny Marr', 'Kurt Cobain'],
  info: 'Shorter 24" scale, bright attack, and versatile switching.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.0,
    stringSpanNut: 1.41, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'strandberg-boden6-ms',
    manufacturer: 'Strandberg',
    model: 'Boden 6 (multi-scale)',
    introduced: 2012,
    country: 'Sweden / Indonesia',
    players: ['Plini', 'Tosin Abasi (aiemmin)'],
  info: 'Headless ergonomics and fanned frets — a modern progressive tool.',
    units: 'inch',
    mode: 'curved',
    strings: 6, frets: 24,
    scaleTreble: 25.0, scaleBass: 25.75, anchorFret: 7,
    stringSpanNut: 1.37, stringSpanBridge: 2.00, overhang: 0.10,
  },
  {
    id: 'ibanez-rgif7',
    manufacturer: 'Ibanez',
    model: 'RGIF7 (multi-scale)',
    introduced: 2014,
    country: 'Indonesia / Japan',
    players: ['Modern metal -soittajat'],
  info: '7-string fan-fret; balanced tension and clear low end.',
    units: 'inch',
    mode: 'curved',
    strings: 7, frets: 24,
    scaleTreble: 25.5, scaleBass: 27.0, anchorFret: 12,
    stringSpanNut: 1.77, stringSpanBridge: 2.28, overhang: 0.12,
  },
  {
    id: 'schecter-hellraiser-c7',
    manufacturer: 'Schecter',
    model: 'Hellraiser C-7',
    introduced: 2006,
    country: 'Korea / Indonesia',
    players: ['Metalli- ja core-skenet laajasti'],
  info: 'Long 26.5" for 7-string; active pickups and modern playability.',
    units: 'inch',
    mode: 'equal',
    strings: 7, frets: 24, scale: 26.5,
    stringSpanNut: 1.77, stringSpanBridge: 2.28, overhang: 0.12,
  },
  {
    id: 'ibanez-rg2228',
    manufacturer: 'Ibanez',
    model: 'RG2228 (8-string)',
    introduced: 2007,
    country: 'Japan',
    players: ['Mårten Hagström', 'Fredrik Thordendal', 'Tosin Abasi (varh.)'],
  info: 'Among the first mass-produced 8-strings; a djent cornerstone.',
    units: 'inch',
    mode: 'equal',
    strings: 8, frets: 24, scale: 27.0,
    stringSpanNut: 2.13, stringSpanBridge: 2.75, overhang: 0.12,
  },
  {
    id: 'kiesel-vader6-ms',
    manufacturer: 'Kiesel',
    model: 'Vader 6 (multi-scale)',
    introduced: 2014,
    country: 'USA',
    players: ['Moni moderni prog-soittaja'],
  info: 'Headless fan-fret; compact, rigid, and lightweight.',
    units: 'inch',
    mode: 'curved',
    strings: 6, frets: 24,
    scaleTreble: 25.0, scaleBass: 25.5, anchorFret: 9,
    stringSpanNut: 1.38, stringSpanBridge: 2.00, overhang: 0.10,
  },
  {
    id: 'gibson-flying-v-58',
    manufacturer: 'Gibson',
    model: 'Flying V ’58',
    artist: 'Albert King',
    introduced: 1958,
    country: 'USA',
    players: ['Albert King', 'K.K. Downing', 'Michael Schenker'],
  info: 'Modernist “space-age” shape that found its audience later.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.43, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'gibson-explorer-58',
    manufacturer: 'Gibson',
    model: 'Explorer ’58',
    artist: 'Allen Collins',
    introduced: 1958,
    country: 'USA',
    players: ['Allen Collins', 'James Hetfield', 'The Edge'],
  info: 'Angular classic — built for hard rock and metal.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.43, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'brian-may-red-special',
    manufacturer: 'Brian May',
    model: 'Red Special',
    artist: 'Brian May',
    introduced: 1963,
    country: 'UK',
    players: ['Brian May'],
  info: 'Home-built semi-hollow — the core of the Queen sound.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 24.0,
    stringSpanNut: 1.46, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'charvel-san-dimas',
    manufacturer: 'Charvel',
    model: 'San Dimas Style 1',
    introduced: 1979,
    country: 'USA',
    players: ['Jake E. Lee', 'Guthrie Govan (myöh. signature)'],
  info: 'Hot-rod superstrat for the 1980s shred era.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 25.5,
    stringSpanNut: 1.42, stringSpanBridge: 2.11, overhang: 0.11,
  },
  {
    id: 'esp-eclipse',
    manufacturer: 'ESP',
    model: 'Eclipse',
    introduced: 1995,
    country: 'Japan',
    players: ['James Hetfield (ESP single-cutit)', 'Bill Kelliher'],
  info: 'Single-cut with a modern touch — a rock/metal all-rounder.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.42, stringSpanBridge: 2.00, overhang: 0.12,
  },
  {
    id: 'parker-fly',
    manufacturer: 'Parker',
    model: 'Fly',
    introduced: 1993,
    country: 'USA',
    players: ['Adrian Belew', 'Reeves Gabrels'],
  info: 'Carbon-reinforced, extremely lightweight, and modern 1990s innovation.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 25.5,
    stringSpanNut: 1.40, stringSpanBridge: 2.05, overhang: 0.11,
  },
  {
    id: 'gibson-firebird',
    manufacturer: 'Gibson',
    model: 'Firebird',
    introduced: 1963,
    country: 'USA',
    players: ['Johnny Winter', 'Eric Clapton (Firebird)'],
  info: 'Reverse body with mini-humbuckers — a distinctive 60s design.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 22, scale: 24.75,
    stringSpanNut: 1.42, stringSpanBridge: 2.02, overhang: 0.12,
  },
  {
    id: 'tele-thinline',
    manufacturer: 'Fender',
    model: 'Telecaster Thinline',
    introduced: 1968,
    country: 'USA',
    players: ['Jonny Greenwood', 'Graham Coxon'],
  info: 'Chambered Tele — lighter with an airier sound.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 21, scale: 25.5,
    stringSpanNut: 1.41, stringSpanBridge: 2.08, overhang: 0.12,
  },
  {
    id: 'musicman-jp6',
    manufacturer: 'Music Man',
    model: 'JP6',
    artist: 'John Petrucci',
    introduced: 2001,
    country: 'USA',
    players: ['John Petrucci'],
  info: 'Tailored for virtuosos — precise and versatile 25.5" tool.',
    units: 'inch',
    mode: 'equal',
    strings: 6, frets: 24, scale: 25.5,
    stringSpanNut: 1.41, stringSpanBridge: 2.08, overhang: 0.11,
  },

  // ---------------- B A S S E S ----------------
  {
    id: 'fender-precision',
    manufacturer: 'Fender',
    model: 'Precision Bass',
    artist: 'James Jamerson',
    introduced: 1951,
    country: 'USA',
    players: ['James Jamerson', 'Steve Harris', 'Pino Palladino'],
  info: 'The first successful electric bass — warm, punchy fundamental tone.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 20, scale: 34.0,
    stringSpanNut: 1.50, stringSpanBridge: 2.25, overhang: 0.12,
  },
  {
    id: 'fender-jazz-bass',
    manufacturer: 'Fender',
    model: 'Jazz Bass',
    artist: 'Jaco Pastorius',
    introduced: 1960,
    country: 'USA',
    players: ['Jaco Pastorius', 'Geddy Lee', 'Marcus Miller'],
  info: 'Narrow neck, two pickups — articulate and versatile.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 20, scale: 34.0,
    stringSpanNut: 1.50, stringSpanBridge: 2.25, overhang: 0.12,
  },
  {
    id: 'rickenbacker-4001',
    manufacturer: 'Rickenbacker',
    model: '4001',
    artist: 'Paul McCartney / Chris Squire',
    introduced: 1961,
    country: 'USA',
    players: ['Paul McCartney', 'Chris Squire', 'Lemmy Kilmister'],
  info: 'Neck-through design with a bright, piano-like attack.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 20, scale: 33.25,
    stringSpanNut: 1.63, stringSpanBridge: 2.25, overhang: 0.12,
  },
  {
    id: 'musicman-stingray',
    manufacturer: 'Music Man',
    model: 'StingRay',
    artist: 'Bernard Edwards / Flea',
    introduced: 1976,
    country: 'USA',
    players: ['Bernard Edwards', 'Louis Johnson', 'Flea'],
  info: 'Active electronics with a large humbucker — an iconic slap sound.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 21, scale: 34.0,
    stringSpanNut: 1.57, stringSpanBridge: 2.28, overhang: 0.12,
  },
  {
    id: 'hofner-violin-bass',
    manufacturer: 'Höfner',
    model: '500/1 Violin Bass',
    artist: 'Paul McCartney',
    introduced: 1956,
    country: 'Germany',
    players: ['Paul McCartney'],
  info: 'Light short-scale with a soft, woody tone — a symbol of the Beatles’ early years.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 22, scale: 30.0,
    stringSpanNut: 1.50, stringSpanBridge: 2.05, overhang: 0.12,
  },
  {
    id: 'gibson-thunderbird',
    manufacturer: 'Gibson',
    model: 'Thunderbird',
    artist: 'Nikki Sixx',
    introduced: 1963,
    country: 'USA',
    players: ['Nikki Sixx', 'John Entwistle', 'Krist Novoselic'],
  info: 'Reverse body and neck-through construction — warm sustain and attitude.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 20, scale: 34.0,
    stringSpanNut: 1.60, stringSpanBridge: 2.25, overhang: 0.12,
  },
  {
    id: 'dingwall-ng2',
    manufacturer: 'Dingwall',
    model: 'NG-2 (5-string, multi-scale)',
    artist: 'Adam “Nolly” Getgood',
    introduced: 2015,
    country: 'Canada',
    players: ['Adam "Nolly" Getgood'],
  info: '37–34" fan-fret: very tight low B and modern clarity.',
    units: 'inch',
    mode: 'curved',
    strings: 5, frets: 24,
    scaleTreble: 34.0, scaleBass: 37.0, anchorFret: 12,
    stringSpanNut: 1.77, stringSpanBridge: 2.95, overhang: 0.12,
  },
  {
    id: 'warwick-thumb',
    manufacturer: 'Warwick',
    model: 'Thumb BO',
    introduced: 1985,
    country: 'Germany',
    players: ['Stuart Zender', 'Ryan Martinie', 'P-Nut'],
  info: 'German classic — pronounced mids and 24 frets.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 24, scale: 34.0,
    stringSpanNut: 1.50, stringSpanBridge: 2.36, overhang: 0.12,
  },
  {
    id: 'spector-ns2',
    manufacturer: 'Spector',
    model: 'NS-2',
    introduced: 1979,
    country: 'USA',
    players: ['Mike Inez', 'Alex Webster', 'Rex Brown'],
  info: 'Curved NS body and solid rock tone since the 1980s.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 24, scale: 34.0,
    stringSpanNut: 1.64, stringSpanBridge: 2.26, overhang: 0.12,
  },
  {
    id: 'yamaha-bb',
    manufacturer: 'Yamaha',
    model: 'BB (esim. BBP34)',
    introduced: 1977,
    country: 'Japan',
    players: ['Pino Palladino', 'Nathan East', 'Peter Hook'],
  info: 'P-/J-inspired workhorse — even and precise.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 21, scale: 34.0,
    stringSpanNut: 1.57, stringSpanBridge: 2.28, overhang: 0.12,
  },
  {
    id: 'fender-mustang-bass',
    manufacturer: 'Fender',
    model: 'Mustang Bass',
    introduced: 1966,
    country: 'USA',
    players: ['Tina Weymouth', 'Justin Meldal-Johnsen'],
    info: 'Short-scale 30" – helppo soitettavuus ja vintage-henki.',
    units: 'inch',
    mode: 'equal',
    strings: 4, frets: 19, scale: 30.0,
    stringSpanNut: 1.50, stringSpanBridge: 2.25, overhang: 0.12,
  },
  {
    id: 'ibanez-sr505',
    manufacturer: 'Ibanez',
    model: 'SR505 (5-string)',
    introduced: 2000,
    country: 'Indonesia / Japan',
    players: ['Monia modernin musiikin basisteja'],
    info: 'Soundgear-sarjan ohut kaula ja moderni monipuolisuus.',
    units: 'inch',
    mode: 'equal',
    strings: 5, frets: 24, scale: 34.0,
    stringSpanNut: 1.77, stringSpanBridge: 2.75, overhang: 0.12,
  },
]
